### ISSUE TITLE
抛砖引玉下

### ISSUE THREAD

**Issue by nchen194** [uselibrary/Getting-Started-with-Linux#5]
我不知道怎么加到首页里，就在这里提交了，大佬看看等不能用
我写一下我常用的几个docker命令，才疏学浅见笑了
1、docker ps与docker ps -la
他们的区别在于加上-la之后可以把启动失败或者未运行的容器，里面的CONTAINER ID参数后面一些操作可以用到（一串12位字符）
2、docker start、docker stop、docker restart
容器的启动、暂停、重启，这些命令后面需要加上CONTAINER ID，如：docker restart 2f4e6f3964gE
有一个小技巧可以对所有容器操作不过有点简单粗暴，在操作的命令后面加 $(docker ps -la)，拿重启举例：docker restart $(docker ps -la)
3、docker rm和docker rmi
这两都是删除，区别在于一个删除容器一个删除容器的镜像，不过两个都要带CONTAINER ID参数，运行前都要先把容器停了

**Comment by uselibrary** [comment]
感谢补充，周末将再整理一批常见命令，一起添加。再次感谢！

**Comment by nchen194** [comment]
众人拾柴火焰高，现在很多linux书感觉实用性不强，希望这以后是linux权威内容

**Comment by uselibrary** [comment]
已添加并更新内容
